# Linear Algebra

In [5]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


/usr/local/lib/python2.7/dist-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['interp']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


- - - 

In [6]:
#NumPy Arrays
M1 = np.array( [[5,-4,0],[-4,7,-3],[0,-3,5]] )
M1

array([[ 5, -4,  0],
       [-4,  7, -3],
       [ 0, -3,  5]])

## Matrix diagonalization
We start again with the matrix equation, capitol bold letters denotes matrices
\begin{equation}
  \boldsymbol{A}\boldsymbol{X}=\boldsymbol{B}\,,
\end{equation}
where $\boldsymbol{A}$ is an $n \times n$ matrix.

We know that there exists a bi-diagonal transformación such that
\begin{equation}
  \boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{U}=\boldsymbol{A}_{\text{diag}}
\end{equation}
So, by doing standard operations we have
\begin{align}
  \boldsymbol{V}^\dagger \boldsymbol{A} \boldsymbol{U} \boldsymbol{U}^\dagger \boldsymbol{X}=& \boldsymbol{V}^\dagger \boldsymbol{B}\\
  \boldsymbol{A}_{\text{diag}} \boldsymbol{X}'=&\boldsymbol{B}'\,,      
\end{align}
where
\begin{align}
  \boldsymbol{X}=& \boldsymbol{U}\boldsymbol{X}'\,, &    \boldsymbol{B}=& \boldsymbol{V}\boldsymbol{B}'\,.
\end{align}

If $\boldsymbol{A}_{\text{diag}}=\operatorname{diag}(\lambda_1,\lambda_2,\ldots \lambda_n)$, $\boldsymbol{X}^{\operatorname{T}}=(x_1\ x_2\ x_3)^{\operatorname{T}}$ and $\boldsymbol{B}^{\operatorname{T}}=(b_1\ b_2\ b_3)^{\operatorname{T}}$,
the solution of the system is given by
\begin{equation}
\lambda_i x'_i=b_i'\,.
\end{equation}

 A suitable way to introduce this method is applying it to some basic problem. To do so, let's take the result of the [Example 1](#Example-1):

$$ \begin{bmatrix}
5 & -4 & 0 \\
-4 & 7 & -3 \\ 
0 & -3 & 5
\end{bmatrix}
\begin{bmatrix}
x_{1} \\
x_{2} \\
x_{3} 
\end{bmatrix}  =
\begin{bmatrix}
1 \\
0 \\
-2
\end{bmatrix}
$$
As the matrix is symmetric $\boldsymbol{V}=\boldsymbol{U}$ and $\boldsymbol{U}^\dagger=\boldsymbol{U}^{\operatorname{T}}$ 

In [11]:
A=M1
np.linalg.eig?

In [8]:
B=np.array([[1],[0],[-2]])
B

array([[ 1],
       [ 0],
       [-2]])

In [9]:
A_diag,V=np.linalg.eig( A )

In [50]:
A_diag
A_diag=np.diag(A_diag)

## Check V is an ortogonal matrix
    

In [21]:
Vt=np.transpose(V)
Ident=np.dot(V,Vt)

In [18]:
Ident.round(14)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [257]:
V 

array([[ -5.07191124e-01,  -6.18673713e-01,  -6.00000000e-01],
       [  7.73342141e-01,  -6.33988906e-01,   1.91548674e-16],
       [ -3.80393343e-01,  -4.64005285e-01,   8.00000000e-01]])

We first check the proper order of the diagonalization

In [263]:
np.dot(  np.dot( V.transpose(),A  ), V).round(14)

array([[ 11.09901951,   0.        ,   0.        ],
       [  0.        ,   0.90098049,   0.        ],
       [  0.        ,   0.        ,   5.        ]])

If we make
$$ \boldsymbol{U}=[\boldsymbol{U}_1,\boldsymbol{U}_2,\boldsymbol{U}_3], \qquad \boldsymbol{V}=[\boldsymbol{V}_1,\boldsymbol{V}_2,\boldsymbol{V}_3] $$

We know that there exists a bi-diagonal transformación such that
\begin{equation}
  \boldsymbol{A}\,\boldsymbol{U}=\boldsymbol{V}\boldsymbol{A}_{\text{diag}}
\end{equation}
\begin{equation}
  \boldsymbol{A}\,\boldsymbol{U}_i=\lambda_i\boldsymbol{V}_i
\end{equation}

We can use this to check the proper order of the eigenvalues

Since

In [25]:
V0=np.reshape( V[:,0],(3,1))
V1=np.reshape( V[:,1],(3,1))
V2=np.reshape( V[:,2],(3,1))
display(V1)
display(V2)


array([[-0.61867371],
       [-0.63398891],
       [-0.46400528]])

array([[ -6.00000000e-01],
       [  1.91548674e-16],
       [  8.00000000e-01]])

In [26]:
display( np.dot(A,V0) )

array([[-5.62932419],
       [ 8.58333952],
       [-4.22199314]])

In [27]:
A_diag[0]*V0

array([[-5.62932419],
       [ 8.58333952],
       [-4.22199314]])

In [28]:
display( np.dot(A,V1) ), A_diag[1]*V1

array([[-0.55741294],
       [-0.57121163],
       [-0.41805971]])

(None, array([[-0.55741294],
        [-0.57121163],
        [-0.41805971]]))

## Reordenar U de menor a mayor 

In [34]:
U=np.hstack((V1,V2,V0))
np.dot(  np.dot( U.transpose(),A  ), U).round(14)

array([[  0.90098049,   0.        ,   0.        ],
       [  0.        ,   5.        ,   0.        ],
       [  0.        ,   0.        ,  11.09901951]])

## Reordenar de mayor a menor

In [35]:
U=np.hstack((V0,V2,V1))
np.dot(  np.dot( U.transpose(),A  ), U).round(14)

array([[ 11.09901951,   0.        ,   0.        ],
       [  0.        ,   5.        ,   0.        ],
       [  0.        ,   0.        ,   0.90098049]])

In [63]:
Bp=np.dot(V.transpose(),B)
Xp=np.dot(np.linalg.inv(A_diag),Bp)
Bp

array([[ 0.25359556],
       [ 0.30933686],
       [-2.2       ]])

## Soluciones

In [60]:
X=np.dot(V,Xp)
X

array([[ 0.04],
       [-0.2 ],
       [-0.52]])

In [62]:
np.dot(A,X).round(14)

array([[ 1.],
       [ 0.],
       [-2.]])

In [248]:
np.linalg.det(M1-bI)