In [1]:
import numpy as np
import sympy
sympy.init_printing()
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Se buscan las soluciones del siguiente sistema de ecuaciones lineales:

$$ \left[ \matrix{
2 & -1 & 1 \\
-1 & 3 & -2 \\ 
1 & -2 & 4
}\right] 
\left[ \matrix{
x_{1} \\
x_{2} \\
x_{3} 
}\right]  =
\left[ \matrix{
1 \\
2 \\
0
}\right]$$


In [2]:
M = np.matrix([[2,-1,1],[-1,3,-2],[1,-2,4]])

In [3]:
A=M

In [4]:
A_diag,V=np.linalg.eig(A)

In [5]:
A_diag=np.diag(A_diag)
sympy.Matrix(A_diag)

⎡6.0489173395223        0.0               0.0      ⎤
⎢                                                  ⎥
⎢      0.0        1.64310413210779        0.0      ⎥
⎢                                                  ⎥
⎣      0.0              0.0         1.3079785283699⎦

**1) Prueba de que V es ortogonal**

In [6]:
Vt=np.transpose(V)
I=np.dot(V,Vt)

We first check the proper order of the diagonalization

In [7]:
sympy.Matrix(np.dot(np.dot( V.transpose(),A ), V).round(14))

⎡6.04891733952231        0.0               0.0      ⎤
⎢                                                   ⎥
⎢      0.0         1.64310413210779        0.0      ⎥
⎢                                                   ⎥
⎣      0.0               0.0         1.3079785283699⎦

If we make
$$ \boldsymbol{U}=[\boldsymbol{U}_1,\boldsymbol{U}_2,\boldsymbol{U}_3], \qquad \boldsymbol{V}=[\boldsymbol{V}_1,\boldsymbol{V}_2,\boldsymbol{V}_3] $$

We know that there exists a bi-diagonal transformación such that
\begin{equation}
  \boldsymbol{A}\,\boldsymbol{U}=\boldsymbol{V}\boldsymbol{A}_{\text{diag}}
\end{equation}
\begin{equation}
  \boldsymbol{A}\,\boldsymbol{U}_i=\lambda_i\boldsymbol{V}_i
\end{equation}

We can use this to check the proper order of the eigenvalues

In [8]:
V0=np.reshape( V[:,0],(3,1))
V1=np.reshape( V[:,1],(3,1))
V2=np.reshape( V[:,2],(3,1))
display(V0)
display(V1)
display(V2)

matrix([[-0.32798528],
        [ 0.59100905],
        [-0.73697623]])

matrix([[ 0.73697623],
        [-0.32798528],
        [-0.59100905]])

matrix([[ 0.59100905],
        [ 0.73697623],
        [ 0.32798528]])

In [9]:
display(( np.dot(A,V0) )),display((A_diag[0,0]*V0))

matrix([[-1.98395583],
        [ 3.57496488],
        [-4.45790829]])

matrix([[-1.98395583],
        [ 3.57496488],
        [-4.45790829]])

(None, None)

In [10]:
display(np.dot(A,V1)), display(A_diag[1,1]*V1)

matrix([[ 1.21092869],
        [-0.53891396],
        [-0.97108941]])

matrix([[ 1.21092869],
        [-0.53891396],
        [-0.97108941]])

(None, None)

**2) Reordenando U de menor a mayor **

In [11]:
U=np.hstack((V2,V1,V0))
sympy.Matrix(np.dot(np.dot(U.transpose(),A), U).round(14))

⎡1.3079785283699        0.0               0.0       ⎤
⎢                                                   ⎥
⎢      0.0        1.64310413210779        0.0       ⎥
⎢                                                   ⎥
⎣      0.0              0.0         6.04891733952231⎦

**3) Reordenando U de mayor a menor**

In [12]:
U=np.hstack((V0,V1,V2))
sympy.Matrix(np.dot(np.dot( U.transpose(),A ), U).round(14))

⎡6.04891733952231        0.0               0.0      ⎤
⎢                                                   ⎥
⎢      0.0         1.64310413210779        0.0      ⎥
⎢                                                   ⎥
⎣      0.0               0.0         1.3079785283699⎦

**4) Soluciones**

In [13]:
B=np.array([[1],[2],[0]])

In [14]:
Bp=np.dot(V.transpose(),B)
Xp=np.dot(np.linalg.inv(A_diag),Bp)
Bp

matrix([[ 0.85403282],
        [ 0.08100567],
        [ 2.06496151]])

In [15]:
X=np.dot(V,Xp)
print("Las soluciones al sistema de ecuaciones lineales son: \nx1={} \nx2={} \nx3={}".format(X[0],X[1],X[2]))

Las soluciones al sistema de ecuaciones lineales son: 
x1=[[ 0.92307692]] 
x2=[[ 1.23076923]] 
x3=[[ 0.38461538]]
