# Matrix diagonalization

## Theorem 1

If $\boldsymbol{A}$ is Hermitic, e.g:
\begin{align}
\boldsymbol{A}^\dagger =\boldsymbol{A}\,,
\end{align}
Then exists an _unitary  matrix_ $\boldsymbol{V}$ e.g:
\begin{align}
\boldsymbol{V}^{\ -1}=\boldsymbol{V}^\dagger \,,
\end{align}
such that
\begin{equation}
  \boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{V}=\boldsymbol{A}_{\text{diag}}\,,
\end{equation}
where 
$\boldsymbol{A}_{\text{diag}}=\operatorname{diag}(\lambda_1,\lambda_2,\ldots \lambda_n)$ is the diagonalized mass matrix.

### Corollary 1

If $\boldsymbol{A}$ is symmetric, e.g:
\begin{align}
\boldsymbol{A}^{\operatorname{T}} =\boldsymbol{A}\,,
\end{align}
Then exists an _ortogonal matrix_ $\boldsymbol{V}$, e.g:
\begin{align}
\boldsymbol{V}^{-1}=\boldsymbol{V}^{\operatorname{T}} \,,
\end{align}
such that
\begin{equation}
  \boldsymbol{V}^{\operatorname{T}}\boldsymbol{A}\,\boldsymbol{V}=\boldsymbol{A}_{\text{diag}}\,,
\end{equation}
where 
$\boldsymbol{A}_{\text{diag}}=\operatorname{diag}(\lambda_1,\lambda_2,\ldots \lambda_n)$ is the diagonalized mass matrix.

## Eigenvector problem
The __Corollary__ only guarantees existence. Tor really calculate de diagonalization matrix we must establish the eigenvector problem:

In the case a symetric matrix, the eigenvalue equation is just:
\begin{align}
%$$
  \boldsymbol{A}\,\boldsymbol{V}_i=&\lambda_i\boldsymbol{V}_i \nonumber\\
  \boldsymbol{A}\,\boldsymbol{V}_i-\lambda_i\boldsymbol{V}_i=&\boldsymbol{0} \nonumber\\
  (\boldsymbol{A}-\lambda_i \,\boldsymbol{I})\boldsymbol{V}_i=&\boldsymbol{0}\,,
%$$
\end{align}
where $\boldsymbol{V}_i$ is the $i$-th column of the matrix  $\boldsymbol{V}$, and $\boldsymbol{I}$ is the identity matrix. 

To avoid the trivial solution $\boldsymbol{V}_i=\boldsymbol{0}$, we require that $\boldsymbol{A}-\lambda_i\, \boldsymbol{I}$
does not have an inverse, or equivalently
$$\det( \boldsymbol{A}-\lambda_i\, \boldsymbol{I})=0\,.$$

## Theorem 2: Singular value decomposition (SVD)
See [SVD](https://en.wikipedia.org/wiki/Singular_value_decomposition) (where the  Hermetique-conjugate is denoted with "*" instead that with "")

A general complex matrix $\boldsymbol{A}$  can be diagonalized by a bi-diagonal transformation such that
\begin{equation}
  \boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{U}=\boldsymbol{A}_{\text{diag}}\,,
\end{equation}
where 
$\boldsymbol{A}_{\text{diag}}=\operatorname{diag}(\lambda_1,\lambda_2,\ldots \lambda_n)$ is the diagonalized mass matrix.

### Demostration
\begin{align}
  \boldsymbol{A}_{\text{diag}}=&\boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{U}\\
  \boldsymbol{A}_{\text{diag}}\boldsymbol{A}_{\text{diag}}^\dagger=&\boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{U}
  \left(\boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{U}\right)^\dagger\\
  =&\boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{U}
  \left(   \boldsymbol{U}^\dagger \boldsymbol{A}^\dagger\,\boldsymbol{V}\right)\\
  =&\boldsymbol{V}^\dagger
  \left( \boldsymbol{A}  \boldsymbol{A}^\dagger\,\right) \boldsymbol{V}\,.\\
\end{align}
Since $\boldsymbol{A}  \boldsymbol{A}^\dagger$ is hermitic and $\boldsymbol{A}  \boldsymbol{A}^\dagger$ is diagonal, then in fact there exists an unitary matrix $\boldsymbol{V}$.  Similarly there exists an unitary matrix $\boldsymbol{U}$ which diagonalizes  $\boldsymbol{A}^\dagger  \boldsymbol{A}$

### Scipy implementation
The implementation in scipy is based in the inverted relation 
\begin{align}
  \boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{U}=&\boldsymbol{A}_{\text{diag}}\\
  \boldsymbol{V}\boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{U}\boldsymbol{U}^\dagger=&\boldsymbol{V}\boldsymbol{A}_{\text{diag}}\boldsymbol{U}^\dagger\\
  \boldsymbol{A}=&\boldsymbol{V}\boldsymbol{A}_{\text{diag}}\boldsymbol{U}^\dagger\,.
\end{align}

The implementation is trough the module `scipy.linalg.svd`:
```bash
V,Adiag,Udagger=linalg.svd(A)
```


### Eigenvectors and eigenvalues
If we make
$$ \boldsymbol{U}=[\boldsymbol{U}_1,\boldsymbol{U}_2,\boldsymbol{U}_3], \qquad \boldsymbol{V}=[\boldsymbol{V}_1,\boldsymbol{V}_2,\boldsymbol{V}_3] $$

We know that there exists a bi-diagonal transformación such that
\begin{equation}
%$$
  \boldsymbol{A}\,\boldsymbol{U}=\boldsymbol{V}\boldsymbol{A}_{\text{diag}}
\end{equation}
\begin{equation}
  \boldsymbol{A}\,\boldsymbol{U}_i=\lambda_i\boldsymbol{V}_i
%$$
\end{equation}
not sum upon $i$. Here 
* $\lambda_i$ are called eigenvalues
* $V_i$ and $U_i$ are the eigenvectors

We can use this to check the proper order of the eigenvalues

## Transformation of a linear system
We start again with the matrix equation, capitol bold letters denotes matrices
\begin{equation}
  \boldsymbol{A}\boldsymbol{X}=\boldsymbol{B}\,,
\end{equation}
where $\boldsymbol{A}$ is an $n \times n$ matrix.

We know that there exists a bi-diagonal transformación such that
\begin{equation}
  \boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{U}=\boldsymbol{A}_{\text{diag}}
\end{equation}
So, by doing standard operations we have
\begin{align}
  \boldsymbol{V}^\dagger \boldsymbol{A} \boldsymbol{U} \boldsymbol{U}^\dagger \boldsymbol{X}=& \boldsymbol{V}^\dagger \boldsymbol{B}\\
   \left( \boldsymbol{V}^\dagger \boldsymbol{A} \boldsymbol{U} \right) 
   \left( \boldsymbol{U}^\dagger \boldsymbol{X}\right)=& \boldsymbol{V}^\dagger \boldsymbol{B}\\
  \boldsymbol{A}_{\text{diag}} \boldsymbol{X}'=&\boldsymbol{B}'\,,      
\end{align}
where
\begin{align}
  \boldsymbol{X}'=& \boldsymbol{U}^\dagger \boldsymbol{X}\,, &    \boldsymbol{B}'=& \boldsymbol{V}^\dagger \boldsymbol{B}\,,
\end{align}
or
\begin{align}
  \boldsymbol{X}=& \boldsymbol{U}\boldsymbol{X}'\,, &    \boldsymbol{B}=& \boldsymbol{V}\boldsymbol{B}'\,.
\end{align}

If $\boldsymbol{A}_{\text{diag}}=\operatorname{diag}(\lambda_1,\lambda_2,\ldots \lambda_n)$, $\boldsymbol{X}^{\operatorname{T}}=\begin{pmatrix}x_1 & x_2 &\cdots & x_n\end{pmatrix}^{\operatorname{T}}$ and $\boldsymbol{B}^{\operatorname{T}}=\begin{pmatrix}b_1& b_2 &\cdots & b_n\end{pmatrix}^{\operatorname{T}}$,
the solution of the system is given by
\begin{equation}
\lambda_i x'_i=b_i'\,.
\end{equation}

Note that
\begin{align}
   \boldsymbol{X}'=&\boldsymbol{A}_{\text{diag}}^{-1}\boldsymbol{B}'\,,      
\end{align}
and the final solution is
\begin{align}
   \boldsymbol{X}=&U \boldsymbol{X}'\\ 
               =&U\boldsymbol{A}_{\text{diag}}^{-1}V^\dagger \boldsymbol{B}\,,      
\end{align}
Therefore
$$A^{-1}=U\boldsymbol{A}_{\text{diag}}^{-1}V^\dagger$$

## Example

 A suitable way to introduce this method is applying it to some basic problem. To do so, let's take the result of the [Example 1](#Example-1):

$$ \begin{bmatrix}
5 & -4 & 0 \\
-4 & 7 & -3 \\ 
0 & -3 & 5
\end{bmatrix}
\begin{bmatrix}
x_{1} \\
x_{2} \\
x_{3} 
\end{bmatrix}  =
\begin{bmatrix}
1 \\
0 \\
-2
\end{bmatrix}
$$
As the matrix is symmetric $\boldsymbol{V}=\boldsymbol{U}$ and $\boldsymbol{U}^\dagger=\boldsymbol{U}^{\operatorname{T}}$ 

In [52]:
import numpy as np

In [53]:
M1=np.array([[5,-4,0],
             [-4,7,-3],
             [0,-3,5]])

In [54]:
A=M1
A

array([[ 5, -4,  0],
       [-4,  7, -3],
       [ 0, -3,  5]])

Check if all eigenvalues are different from zero:

In [55]:
np.linalg.det(A)

49.99999999999999

In [57]:
B=np.c_[ [1,0,-2]  ]
B

array([[ 1],
       [ 0],
       [-2]])

Also as 
```python
B=np.array([[1],[0],[-2]])
#or
B=np.reshape(  [1,0,-2],(3,1) )
```

In [58]:
λ,V=np.linalg.eig( A )

In [59]:
A_diag=np.diag(λ)
A_diag

array([[11.09901951,  0.        ,  0.        ],
       [ 0.        ,  0.90098049,  0.        ],
       [ 0.        ,  0.        ,  5.        ]])

In [60]:
V

array([[-5.07191124e-01, -6.18673713e-01, -6.00000000e-01],
       [ 7.73342141e-01, -6.33988906e-01,  1.91548674e-16],
       [-3.80393343e-01, -4.64005285e-01,  8.00000000e-01]])

We first check the proper order of the diagonalization

In [61]:
np.dot(  np.dot( V.transpose(),A  ), V).round(14)

array([[11.09901951,  0.        ,  0.        ],
       [ 0.        ,  0.90098049,  0.        ],
       [ 0.        ,  0.        ,  5.        ]])

Since

In [ ]:
V

array([[ -5.07191124e-01,  -6.18673713e-01,  -6.00000000e-01],
       [  7.73342141e-01,  -6.33988906e-01,   1.91548674e-16],
       [ -3.80393343e-01,  -4.64005285e-01,   8.00000000e-01]])

The final solution is:

In [62]:
A_diag_inv=np.diag(1/λ)
A_diag_inv

array([[0.09009805, 0.        , 0.        ],
       [0.        , 1.10990195, 0.        ],
       [0.        , 0.        , 0.2       ]])

check with `np.linalg.inv(A_diag)`

In [63]:
X=np.dot( np.dot( np.dot( V, np.diag(1/λ) ),V.transpose() ),B)
X

array([[ 0.04],
       [-0.2 ],
       [-0.52]])

__<font color="red">Activity</font>__: Usar np.lingalg.solve

In [ ]:
B.transpose()[0]

array([ 1,  0, -2])

In [ ]:
np.linalg.solve(A,B.transpose()[0])

array([ 0.04, -0.2 , -0.52])

We can now check some properties

In [ ]:
V

array([[-5.07191124e-01, -6.18673713e-01, -6.00000000e-01],
       [ 7.73342141e-01, -6.33988906e-01,  1.91548674e-16],
       [-3.80393343e-01, -4.64005285e-01,  8.00000000e-01]])

In [ ]:
np.c_[ V[: ,0] ]

array([[-0.50719112],
       [ 0.77334214],
       [-0.38039334]])

In [ ]:
A_diag[0,0],λ[0]

(11.099019513592784, 11.099019513592784)

We define the eigenvector $V_i$ as

In [ ]:
V0=np.c_[ V[:,0] ]
V1=np.c_[ V[:,1] ]
V2=np.c_[ V[:,2] ]
display(V0)
display(V1)
V2

array([[-0.50719112],
       [ 0.77334214],
       [-0.38039334]])

array([[-0.61867371],
       [-0.63398891],
       [-0.46400528]])

array([[-6.00000000e-01],
       [ 1.91548674e-16],
       [ 8.00000000e-01]])

In [ ]:
print('{} =\n{}'.format( np.dot(A,V0),λ[0]*V0 ) )

[[-5.62932419]
 [ 8.58333952]
 [-4.22199314]] =
[[-5.62932419]
 [ 8.58333952]
 [-4.22199314]]


Check: $ A V_i=\lambda_i V_i$

Which means the eigenvalue associated to the "operator" $A$ acting on the eigenvector $V_1$

In [ ]:
print('{} =\n{}'.format( np.dot(A,V1),λ[1]*V1 ) )

[[-0.55741294]
 [-0.57121163]
 [-0.41805971]] =
[[-0.55741294]
 [-0.57121163]
 [-0.41805971]]


In [ ]:
print('{} =\n{}'.format( np.dot(A,V2).round(14),
                         (λ[2]*V2).round(14) ) )

[[-3.]
 [ 0.]
 [ 4.]] =
[[-3.]
 [ 0.]
 [ 4.]]


The diagonalization matrix can be rebuild from the eigenvectors

In [ ]:
V

array([[-5.07191124e-01, -6.18673713e-01, -6.00000000e-01],
       [ 7.73342141e-01, -6.33988906e-01,  1.91548674e-16],
       [-3.80393343e-01, -4.64005285e-01,  8.00000000e-01]])

is rebuild with

In [ ]:
U=np.c_[ V0,V1,V2]
U

array([[-5.07191124e-01, -6.18673713e-01, -6.00000000e-01],
       [ 7.73342141e-01, -6.33988906e-01,  1.91548674e-16],
       [-3.80393343e-01, -4.64005285e-01,  8.00000000e-01]])

or with: `np.hstack((V0,V1,V2))`

In [ ]:
np.dot(  np.dot( U.transpose(),A  ), U).round(14)

array([[11.09901951,  0.        ,  0.        ],
       [ 0.        ,  0.90098049,  0.        ],
       [ 0.        ,  0.        ,  5.        ]])

### Eigenvector reordering

__Activity__: https://beta.deepnote.com/project/17b487c8-b092-4032-94f5-438ba4eeb1e9

We can use this to check the proper order of the eigenvalues

In [ ]:
U=np.c_[ V1,V2,V0]
np.dot(  np.dot( U.transpose(),A  ), U).round(14)

array([[ 0.90098049,  0.        ,  0.        ],
       [ 0.        ,  5.        ,  0.        ],
       [ 0.        ,  0.        , 11.09901951]])

The order of eigenvalues can now be changed by changing the order of the eigenvectors and redifining the diagonalization matrix. For example, from small to large. We define first the eigenvalues

In [ ]:
np.sort?

In [ ]:
np.sort( λ)

array([ 0.90098049,  5.        , 11.09901951])

To reverse the order

In [ ]:
np.sort( λ)[::-1]

array([11.09901951,  5.        ,  0.90098049])

In [ ]:
λ

array([ 11.09901951,   0.90098049,   5.        ])

In [64]:
index=np.abs(λ).argsort()
index

array([1, 2, 0])

can be implemented in general with a _comprehensive_ list

In [65]:
V

array([[-5.07191124e-01, -6.18673713e-01, -6.00000000e-01],
       [ 7.73342141e-01, -6.33988906e-01,  1.91548674e-16],
       [-3.80393343e-01, -4.64005285e-01,  8.00000000e-01]])

In [66]:
np.c_[ tuple( [ np.c_[V[:,i]]    for i in range(3) ] ) ]

array([[-5.07191124e-01, -6.18673713e-01, -6.00000000e-01],
       [ 7.73342141e-01, -6.33988906e-01,  1.91548674e-16],
       [-3.80393343e-01, -4.64005285e-01,  8.00000000e-01]])

Changing the order to `index`

In [68]:
U=np.c_[ tuple( [ np.c_[V[:,i]]    for i in np.abs(λ).argsort() ] ) ]
U

array([[-6.18673713e-01, -6.00000000e-01, -5.07191124e-01],
       [-6.33988906e-01,  1.91548674e-16,  7.73342141e-01],
       [-4.64005285e-01,  8.00000000e-01, -3.80393343e-01]])

or: 
```python
n=3
U=np.hstack( [ np.reshape( V[:,i], (n,1) ) for i in index   ] )
```

In [69]:
np.dot(  np.dot( U.transpose(),A  ), U).round(14)

array([[ 0.90098049,  0.        ,  0.        ],
       [ 0.        ,  5.        ,  0.        ],
       [ 0.        ,  0.        , 11.09901951]])

<font color="red">Activity</font>:  Build a function that diagonalize with increasing order in the eigenvalues as a replacement of `np.linalg.eig`
```python
def argeig(A):
    l,V=np.linalg.eig(A)
    ....
    return argl, argV
```



In [ ]:
np.linalg.eig??

In [ ]:
def argeig(a):
    """
    Diagonalize with increasing order in the eigenvalues.
  
    See help(np.linalg.eig)
    """
    l,V=np.linalg.eig(a)
    index=np.abs(l).argsort()
    argl= np.sort( l)
    argV=np.c_[ tuple([ np.c_[ V[:,i]] for i in index   ]) ]
    return argl, argV

In [ ]:
λ,V=argeig(A)
λ,V

(array([ 0.90098049,  5.        , 11.09901951]),
 array([[-6.18673713e-01, -6.00000000e-01, -5.07191124e-01],
        [-6.33988906e-01,  1.91548674e-16,  7.73342141e-01],
        [-4.64005285e-01,  8.00000000e-01, -3.80393343e-01]]))

In [ ]:
np.dot(  np.dot( V.transpose(),A  ), V).round(14)

array([[ 0.90098049,  0.        ,  0.        ],
       [ 0.        ,  5.        ,  0.        ],
       [ 0.        ,  0.        , 11.09901951]])

In [70]:
print( np.linalg.det(A- λ[0]*np.identity(3) ) )
print( np.linalg.det(A- λ[1]*np.identity(3) ) )
np.linalg.det(A- λ[2]*np.identity(3) )

2.4376578809863825e-14
1.6382973032562733e-14


0.0

## General complex matrix

Since
\begin{equation}
  \boldsymbol{A}_{\text{diag}}=\boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{U}
\end{equation}

\begin{align}
\boldsymbol{A}_{\text{diag}}\boldsymbol{A}^\dagger_{\text{diag}}=&  (\boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{U})(\boldsymbol{V}^\dagger\boldsymbol{A}\,\boldsymbol{U})^\dagger\nonumber \\
 =& \boldsymbol{V}^\dagger( \boldsymbol{A}\boldsymbol{A}^\dagger)\boldsymbol{V}
\end{align}

\begin{align}
\boldsymbol{A}_{\text{diag}}^\dagger \boldsymbol{A}_{\text{diag}} 
 =& \boldsymbol{U}^\dagger (\boldsymbol{A}^\dagger\boldsymbol{A})\boldsymbol{U}
\end{align}

See

In [71]:
import numpy as np
from scipy import linalg

__Example__:

In [72]:
A=np.array([[ 2.5       ,  6.92820323],
       [-4.33012702,  4.        ]])

In [73]:
A=np.array([[ 6.66674644,  3.13121253],
            [-0.23343505,  5.8902893 ]])

In [76]:
V,diag,Udagger=linalg.svd(A)

In [77]:
U=Udagger.transpose().conjugate()

In [78]:
np.dot( np.dot( V.transpose().conjugate(),A    ), U).round(14)

array([[8., 0.],
       [0., 5.]])

This is important to stablish that the eigenvectors are determined until ordering and permutations

In [79]:
V

array([[-0.8660254, -0.5      ],
       [-0.5      ,  0.8660254]])

In [80]:
U

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [84]:
np.dot( np.transpose(U),U ).round(14)

array([[1., 0.],
       [0., 1.]])

In [85]:
def orthogonal(θ):
    return np.array( [[np.cos(θ) ,np.sin(θ)],
                      [-np.sin(θ),np.cos(θ)]]   )

In [86]:
Vp=orthogonal(np.pi/3)
Vp

array([[ 0.5      ,  0.8660254],
       [-0.8660254,  0.5      ]])

In [87]:
VV=np.c_[ -V[:,1],-V[:,0]  ]
VV

array([[ 0.5      ,  0.8660254],
       [-0.8660254,  0.5      ]])

In [88]:
Up=orthogonal(np.pi/4)
Up

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [89]:
UU=np.c_[ -U[:,1],-U[:,0]  ]
UU

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [90]:
np.dot( np.dot( VV.transpose().conjugate(),A    ), UU).round(14)

array([[5., 0.],
       [0., 8.]])

__Activity__: https://beta.deepnote.com/project/17b487c8-b092-4032-94f5-438ba4eeb1e9

<font color="red">__Activity__</font>: Solve the system
$$ \boldsymbol{A} \boldsymbol{x}=\boldsymbol{B}$$
for the previous $ \boldsymbol{A}$ matrix and
$$\boldsymbol{B}=\begin{bmatrix}
   1\\
   -4\\
   \end{bmatrix}$$

## Mixed terms

Let:
\begin{align}
X' = 
\begin{bmatrix}
B \\ 
W \\
\end{bmatrix}
\end{align}

Consider  the quadratic equation 
\begin{align}
X^{\prime\operatorname{T}} M X^\prime=& \begin{bmatrix}
B & W 
\end{bmatrix}
\begin{bmatrix}
M_{11} & M_{12} \\
M_{12} & M_{22} \\
\end{bmatrix}
\begin{bmatrix}
B \\ 
W \\
\end{bmatrix}\\
=& 
\begin{bmatrix}
B & W 
\end{bmatrix}
\begin{bmatrix}
M_{11}B + M_{12}W \\
M_{12}B + M_{22}W \\
\end{bmatrix}\\
=& 
B( M_{11}B + M_{12}W)+  W ( M_{12}B + M_{22}W )\\
=&M_{11} B^2 + 2M_{12} BW+ M_{22} W^2\,. 
\end{align}
The queadratic equation is in terms of: $M_{11}$, $M_{12}$ y $M_{22}$

We can simplify this expression if we change to a new basis in which $M$ is diagonal, in such a case the crossed terms disappear

\begin{align}
X^{\prime\operatorname{T}} M X^\prime=&X^{\prime\operatorname{T}}V V^{\operatorname{T}} M V V^{\operatorname{T}} X^\prime=...
\end{align}



If we define
\begin{align}
X\equiv
\begin{bmatrix}
A\\
Z
\end{bmatrix}=V^{\operatorname{T}} X \to X^{\operatorname{T}}= X^{\prime\operatorname{T}} V\,,
\end{align}
\begin{align}
M_{\text{diag}}\equiv V^{\operatorname{T}} M V=\begin{bmatrix}
\lambda_1 & 0 \\ 
0 & \lambda_2 \\
\end{bmatrix}\,,
\end{align}


then,
\begin{align}
X^{\prime\operatorname{T}} M X^\prime=&(X^{\prime\operatorname{T}}V) (V^{\operatorname{T}} M V) (V^{\operatorname{T}} X^\prime)\\
=& X^{\operatorname{T}} M_{\text{diag}} X \\
=&  \lambda_1 A^2+\lambda_2 Z^2\,.
\end{align}

In this basis, the quadratic equation is in terms of eigenvalues and mixing angles, like $\theta$ in this case
\begin{align}
V=
\begin{bmatrix}
\cos\theta & \sin\theta\\
-\sin\theta & \cos\theta
\end{bmatrix},
\end{align}
and there are not mixed terms.

The diagonalization of quadratic equations can be straightforwardly  generalized to $n\times n$ matrices


## Activity: Photon and $Z$ mixing

In [ ]:
Consider the following symmetric matrix

<!-- 
sin2θ=0.23
θ=np.arcsin( np.sqrt(sin2θ)  )
print(θ)
MZ=91.1876
GF=1.166371E-5
v=1/np.sqrt(np.sqrt(2)*GF)
g=2*MZ*np.cos(θ)/v
gp=g*np.tan(θ)
gp
-->

In [107]:
import numpy as np

g =0.64996
gp=0.35523
v=246.22046

In [105]:
M=(v**2/4)*np.array([[g**2 ,-g*gp],
                     [-g*gp, gp**2]])

In [106]:
M

array([[ 6402.67629426, -3499.32718938],
       [-3499.32718938,  1912.52692086]])

Chek that the determinant is zero

In [92]:
np.linalg.det(M).round(8)

-0.0

This imply that one egivanlue is zero

In [93]:
np.linalg.eigvals(M).round(12)

array([8315.20321512,   -0.        ])

which means that the matrix rank, the number of non-zero are eigenvalues is 1

In [94]:
np.linalg.matrix_rank(M)

1

In [95]:
λ,V=np.linalg.eig(M)

In [96]:
np.dot( np.dot(V.transpose(),M) , V).round(11)

array([[8315.20321512,    0.        ],
       [   0.        ,   -0.        ]])

In [97]:
λ1=λ[0]
λ2=λ[1]

In [98]:
-V

array([[-0.87749437, -0.47958694],
       [ 0.47958694, -0.87749437]])

In [99]:
θ=-np.arcsin( V[0,1] )

In [100]:
θ

-0.5001839211647364

In [101]:
np.array( [[np.cos(θ), np.sin(θ)],
            [-np.sin(θ),np.cos(θ)]] )

array([[ 0.87749437, -0.47958694],
       [ 0.47958694,  0.87749437]])

In [102]:
MZ=np.sqrt(λ1)
MZ

91.18773610041056

In [103]:
np.sin(θ)**2

0.23000362966286086

θ angulo de mezcla débil

## Appendix

\begin{equation}
  V\boldsymbol{A}_{\text{diag}}=\boldsymbol{A}
\end{equation}

In [92]:
Adiag=np.array( [[5,0],
                 [0,8]] )

In [93]:
A=np.dot( Vp,np.array( Adiag ) )
A

array([[ 2.5       ,  6.92820323],
       [-4.33012702,  4.        ]])

In [94]:
np.dot( Vp.transpose(),A)

array([[5., 0.],
       [0., 8.]])

In [95]:
λ2,V=np.linalg.eig( np.dot( A,A.transpose() ) )
print('sqrt(λ2)={}'.format(np.sqrt(λ2)))
V=np.c_[ -V[:,1],V[:,0]  ]
V

sqrt(λ2)=[8. 5.]


array([[ 0.5      ,  0.8660254],
       [-0.8660254,  0.5      ]])

In [96]:
λ2p,U=np.linalg.eig( np.dot( A.transpose(),A ) )
print(np.sqrt(λ2))
U

[8. 5.]


array([[1., 0.],
       [0., 1.]])

In [97]:
np.dot( np.dot( V.transpose(),A ), U ).round(15)

array([[ 5.,  0.],
       [-0.,  8.]])

In [98]:
np.dot( V.transpose(),A ).round(15)

array([[ 5.,  0.],
       [-0.,  8.]])

Bidiagonal

In [99]:
Adiag=np.array( [[5,0],
                 [0,8]] )

In [100]:
Vp=orthogonal(np.pi/3)
Vp

array([[ 0.5      ,  0.8660254],
       [-0.8660254,  0.5      ]])

In [101]:
Up=orthogonal(np.pi/4)
Up

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

\begin{equation}
  \boldsymbol{V}\boldsymbol{A}_{\text{diag}}\boldsymbol{U}^\dagger=\boldsymbol{A}
\end{equation}

In [102]:
A=np.dot( np.dot( Vp,Adiag ),Up.transpose() )

In [103]:
A

array([[ 6.66674644,  3.13121253],
       [-0.23343505,  5.8902893 ]])

In [104]:
λ2,V=np.linalg.eig( np.dot( A,A.transpose() ) )
print(λ2,np.sqrt(λ2))
V=np.c_[ -V[:,1],V[:,0]  ]
V

[64. 25.] [8. 5.]


array([[ 0.5      ,  0.8660254],
       [-0.8660254,  0.5      ]])

In [105]:
λ2p,U=np.linalg.eig( np.dot( A.transpose(),A ) )
print(np.sqrt(λ2))
U=-U

[8. 5.]


In [106]:
np.dot( np.dot( V.transpose(),A ), U ).round(14)

array([[5., 0.],
       [0., 8.]])

In [107]:
V,U

(array([[ 0.5      ,  0.8660254],
        [-0.8660254,  0.5      ]]), array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

Scipy implementation

In [108]:
λ,Vs=linalg.eig(A,left=False,right=True)
λ

array([6.27851787+0.76171737j, 6.27851787-0.76171737j])

In [109]:
λ,Vs=linalg.eig(A,left=True,right=False)
λ

array([6.27851787+0.76171737j, 6.27851787-0.76171737j])

In [110]:
np.linalg.solve(A,[1,-4])

array([ 0.46037849, -0.66083877])

In [111]:
A

array([[ 6.66674644,  3.13121253],
       [-0.23343505,  5.8902893 ]])

In [112]:
V,diag,Udagger=linalg.svd(A)

In [42]:
np.dotnp.dot( V.transpose().conjugate(),A)

In [43]:
AA

array([[ 4.4408921e-16,  8.0000000e+00],
       [-5.0000000e+00,  8.8817842e-16]])

In [44]:
np.dot(AA  ,Udagger.transpose())

array([[ 8.0000000e+00, -4.4408921e-16],
       [ 8.8817842e-16,  5.0000000e+00]])

In [40]:
Udagger

array([[ 4.4408921e-16, -5.0000000e+00],
       [ 8.0000000e+00,  8.8817842e-16]])

In [29]:
np.dot( V,A,Udagger)

ValueError: output array is not acceptable (must have the right datatype, number of dimensions, and be a C-Array)

In [59]:
V,diag,Udagger=linalg.svd(A)

array([[8., 0.],
       [0., 5.]])