# Numba
Compile numerical functions for faster running

In [2]:
import time
import numpy as np
from numba import jit
import pandas as pd

ImportError: No module named 'numba'

Example of the problem: integer summation

In [5]:
st=time.time()
imax=10000
for i in range(imax):
    for j in range(imax):
        a=i+j

print(time.time()-st)

9.316529273986816


In [11]:
def suma(imax):
    for i in range(imax):
        for j in range(imax):
            a=i+j
    return a

In [12]:
st=time.time()
a=suma(imax)
print(time.time()-st)

4.799173831939697


Precompile the function with `@jit` of `numba`

In [13]:
# jit decorator tells Numba to compile this function.
# The argument types will be inferred by Numba when function is called.
@jit
def suma(imax):
    for i in range(imax):
        for j in range(imax):
            a=i+j
    return a

In [14]:
st=time.time()
a=suma(imax)
print(time.time()-st)

0.09396576881408691


In [23]:
a=pd.DataFrame()# []#0

A more complicated example with arrays

In [24]:
a=np.array( [0,0])
np.concatenate((a,a))

array([0, 0, 0, 0])

In [18]:
# jit decorator tells Numba to compile this function.
# The argument types will be inferred by Numba when function is called.
@jit#(nopython=True)
def suma(imax,a):
    for i in range(imax):
        for j in range(imax):
            a[i]=i+j
    return(a)

In [24]:
imax=10000
s=time.time()
a=np.zeros(imax)
a=suma(imax,a)
print(time.time()-s)        

0.00023245811462402344


In [25]:
s=time.time()
a=np.zeros(imax)
a=suma(imax,a)
print(time.time()-s)        

0.0002434253692626953


In [26]:
s=time.time()
a=np.zeros(imax)
a=suma(imax,a)
print(time.time()-s)        

0.0002474784851074219


In [23]:
>>> x = np.arange(-5, 5, 0.1)
>>> y = np.arange(-5, 5, 0.1)
>>> xx, yy = np.meshgrid(x, y, sparse=True)
>>> z = np.sin(xx**2 + yy**2) / (xx**2 + yy**2)
#>>> h = plt.contourf(x,y,z)

In [73]:
imax

10000

In [81]:
>>> x = np.arange(0, imax, 1)
>>> y = np.arange(0, imax, 1)
>>> xx, yy = np.meshgrid(x, y, sparse=False)
>>> z = xx+yy

In [86]:
xx

array([[   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999],
       ..., 
       [   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999]])

In [20]:
from numba import jit
import numpy as np

@jit(nopython=True)
def f(n):
    #return np.array([ [ [x,y]  for x in range(n) ] for y in range(n) ])
    for y in range(n):
        return np.array([ (x,y)  for x in range(n) ] )

In [21]:
s=time.time()
a=f(10000)
print(time.time()-s)        

NotImplementedError: Failed at nopython (nopython mode backend)
(int64 x 2) cannot be represented as a Numpy dtype

In [19]:
a[[2]]

array([[2, 0]])

In [109]:
a=(1,2)

In [110]:
np.concatenate( (a,a))

array([1, 2, 1, 2])

In [32]:
n_i=101
n_i%10==0

False

In [ ]:
709510,768607,814