# Numba
Compile numerical functions for faster running

In [22]:
import time
import numpy as np
from numba import jit
import pandas as pd

In [71]:
np.linspace?

In [23]:
a=pd.DataFrame()# []#0

In [24]:
a=np.array( [0,0])
np.concatenate((a,a))

array([0, 0, 0, 0])

In [68]:
# jit decorator tells Numba to compile this function.
# The argument types will be inferred by Numba when function is called.
@jit(nopython=True)
def suma(imax,a):
    #a=np.zeros(imax) #np.array( [0,0])#0# pd.DataFrame()# 0
    #b=0
    #f=open('kk.txt','w')
    for i in range(imax):
        for j in range(imax):
            a[i]=i+j#a+1#np.concatenate( ( a,[i,j] ) )
            #a.append(i)
            #if i%1000==0:
                #a.append({'A':b+1})
            #f.write('{}\n'.format(a))
    
    #f.close()
    return(a)

In [70]:
imax=10000
s=time.time()
a=np.zeros(imax)
a=suma(imax,a)
print(time.time()-s)        

0.27274656295776367


In [65]:
s=time.time()
a=np.zeros(imax)
a=suma(imax,a)
print(time.time()-s)        

0.0001850128173828125


In [66]:
s=time.time()
a=np.zeros(imax)
a=suma(imax,a)
print(time.time()-s)        

0.00018334388732910156


In [72]:
>>> x = np.arange(-5, 5, 0.1)
>>> y = np.arange(-5, 5, 0.1)
>>> xx, yy = np.meshgrid(x, y, sparse=True)
>>> z = np.sin(xx**2 + yy**2) / (xx**2 + yy**2)
#>>> h = plt.contourf(x,y,z)

In [73]:
imax

10000

In [81]:
>>> x = np.arange(0, imax, 1)
>>> y = np.arange(0, imax, 1)
>>> xx, yy = np.meshgrid(x, y, sparse=False)
>>> z = xx+yy

In [86]:
xx

array([[   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999],
       ..., 
       [   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999]])

In [20]:
from numba import jit
import numpy as np

@jit(nopython=True)
def f(n):
    #return np.array([ [ [x,y]  for x in range(n) ] for y in range(n) ])
    for y in range(n):
        return np.array([ (x,y)  for x in range(n) ] )

In [21]:
s=time.time()
a=f(10000)
print(time.time()-s)        

NotImplementedError: Failed at nopython (nopython mode backend)
(int64 x 2) cannot be represented as a Numpy dtype

In [19]:
a[[2]]

array([[2, 0]])

In [109]:
a=(1,2)

In [110]:
np.concatenate( (a,a))

array([1, 2, 1, 2])

In [32]:
n_i=101
n_i%10==0

False

In [ ]:
709510,768607,814